- src/org/wikipedia/Wiki.java
> Deprecate getImage() by requiring file as parameter

- src/org/wikipedia/Wiki.java
(cherry picked from commit https://github.com/MarcoFalke/wiki-java-tools/commit/01a070f786288a8ad562fc3463f880fd03957a40)
> Also fetch sha1 in getFileMetadata()

- src/org/wikipedia/Wiki.java
Fixes issue #84
(cherry picked from commit 16a42e32638f58cdfe32fd6b3ccadad5a4c4f221)
> Handle gzipped InputStream

- src/org/wikipedia/Wiki.java
Imo there is no need to keep deprecated and redundant code. It should be noted that ```Files.readAllBytes()``` requires java 7 but we are already using "try with resources" which requires java 7 anyway.
Is there any place which states the minimum java version needed to run Wiki.java?
> Remove deprecated and redundant code in getImage()

- src/org/wikipedia/Wiki.java
This should avoid some NullPointerExceptions
> Proper use of user.isAllowedTo()

- src/org/wikipedia/Wiki.java
This fixes
* Sometimes pointless sleep *after* ```edit()```
* Often too much throttle between two calls of ```edit()```
> Proper use of throttle()

- src/org/wikipedia/Wiki.java
Maybe a new wrapper for encode should be created. Sth. like ```encode(String text, boolean normalize);```
> Proper use of normalize()

- src/org/wikipedia/Wiki.java
Adjust the white space to how other programs do this now.
> User agent format cleanup

- src/org/wikipedia/Wiki.java
Imo, this cleans things up a bit.
> New method encode(String text, boolean normalize)

- src/org/wikipedia/Wiki.java
- src/org/wikiutils/ParseUtils.java
These are the last to changes I had in my fork. bc61e0e might need more work.
> Last diffs from my branch

- src/org/wikipedia/Wiki.java
I’m terribly sorry, but I managed to create a copy and paste-error in yesterdays pull-request. However, all good things are three (german figure of speech) and it’s all right now.
> Fix variable-name

- src/org/wikipedia/Wiki.java
The current version may throw a ConcurrentModificationException.
> Refactor filling of namespacecache and synchronize it

- src/org/wikipedia/Wiki.java
If I am not mistaken, this improves the performance from O(titles.length^2) to O(titles.length).
> [Wiki.java] worst case performance in getPageText: O(n^2) to O(n)

- src/org/wikipedia/Wiki.java
> [Wiki.java] checkLag: Retry in case of equality

- .travis.yml
- Readme.md
Create .travis.yml / Add travis badge
> add Travis CI support

- .travis.yml
- Readme.md
- pom.xml
code coverage: add  plugin to pom.xml / codecov.io upload && add  badge
> add Codecov.io support

- pom.xml
- test/org/wikipedia/AdminUnitTests.java
- test/org/wikipedia/ArrayUtilsTest.java
- test/org/wikipedia/EventsTest.java
- test/org/wikipedia/ExternalLinksTest.java
- test/org/wikipedia/LoggedInUnitTests.java
- test/org/wikipedia/MathsAndStatsTest.java
- test/org/wikipedia/PagesTest.java
- test/org/wikipedia/RevisionsTest.java
- test/org/wikipedia/UsersTest.java
- test/org/wikipedia/WMFWikiTest.java
- test/org/wikipedia/WikiTest.java
- test/org/wikipedia/WikitextUtilsTest.java
- test/org/wikipedia/servlets/ServletUtilsTest.java
- test/org/wikipedia/tools/ArticleEditorIntersectorTest.java
- test/org/wikipedia/tools/CommandLineParserTest.java
- test/org/wikipedia/tools/ContributionSurveyorTest.java
- test/org/wikipedia/tools/ExternalLinkPopularityTest.java
- test/org/wikipedia/tools/GapFillingTextSearchTest.java
- test/org/wikipedia/tools/UserLinkAdditionFinderTest.java
- test/org/wikiutils/ParseUtilsTest.java
Create PR for testing purposes.
> Upgrade tests to JUnit Jupiter

- src/org/wikipedia/Wiki.java
- src/org/wikiutils/ParseUtils.java
- test/org/wikipedia/WikiTest.java
> Vectorize whatLinksHere and whatTranscludesHere.

- src/org/wikipedia/WMFWiki.java
- test/org/wikipedia/WMFWikiTest.java
> WMFWiki: add the ability to fetch pages as plain text

- src/org/wikipedia/Wiki.java
Since last week, MW started serving both `set-cookie` and `Set-Cookie` header fields upon `action=login` response. Wiki.java is only prepared for dealing with the latter, whereas session cookie is now provided in the former. As a result, successive API requests cannot forward the session cookie to the server and login actions fail.
This patch merges cookie values stored under both map keys and traverses them using Java 8 techniques to populate the local cookie storage.
See also:
* https://phabricator.wikimedia.org/T249680
* https://github.com/MER-C/wiki-java/issues/157
> Fix cookie response header duplicity: ignore case and group values

- src/org/wikipedia/Wiki.java
- test/org/wikipedia/WikiTest.java
Behavior (breaking?) changes:
* `resolveRedirects` now normalizes all input titles as a side effect
* `resolveRedirectParser` (protected) no longer matches against normalized inputs
* `constructTitleString` (protected) now skips internal title normalization
Incidentally:
* fixed parsing of special and media `<page>` elements in `getPageInfo`
* `getFileMetadata` and `getCategoryMemberCounts` have learned to resolve titles
* updated unit tests for `getImagesOnPage` and `whatLinksHere`
* removed stray print line in `parseLogEntry`
A few words regarding `constructTitleString`. Apparently, it was supposed to comply with MW API usage guidelines. Quoting the following points from the [API etiquette](https://www.mediawiki.org/w/index.php?title=API:Main_page&oldid=2855599#API_etiquette) which I …
> Parse results of server-side title normalization
